---
- name: Install dependencies
  hosts: localhost
  tasks:
  - name: Check if docker is installed
    shell: command -v docker
    register: docker_exists
    ignore_errors: yes
  - name: Install docker
    shell:
      cmd: curl -fsSL https://get.docker.com | sh
      warn: False
    when: docker_exists.stdout | length == 0
  - name: Install docker and docker-compose python libs
    pip:
      name:
        - docker
        - docker-compose


- name: Run main playbook for the first time
  import_playbook: playbook.yml

- name: Set up future scheduled runs
  hosts: localhost
  vars:
    timeout_seconds: "90"
    random_delay_seconds: "120"
    schedule_frequency: 10m
    ansible_pull_command: >-
      /usr/local/bin/ansible-pull
      --directory /var/ansible-deployments
      --checkout master
      --url git://github.com/cyrusroshan/ansible-pull-example
      playbook.yml
  tasks:
  - name: Create the systemd unit file
    copy:
      content: |
        [Unit]
        Description=Runs deployments via ansible-pull

        [Service]
        User=root
        ExecStart={{ ansible_pull_command }}
        TimeoutSec={{ timeout_seconds }}

      dest: "/etc/systemd/system/ansible-deployments.service"
  - name: Create the systemd timer
    copy:
      content: |
        [Unit]
        Description=Schedule ansible-deployments.service

        [Timer]
        OnBootSec=5min
        OnUnitActiveSec={{ schedule_frequency }}
        RandomizedDelaySec={{ random_delay_seconds }}

        [Install]
        WantedBy=timers.target
      dest: "/etc/systemd/system/ansible-deployments.timer"
  - name: Reload the systemd daemon and start the timer
    systemd:
      name: ansible-deployments.timer
      enabled: yes
      state: started
      daemon_reload: yes
